language: cpp

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt-5.15.2-focal
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt515base qt515tools qt515translations 
- sudo apt-get install -qq qt515svg qt515wayland libgl-dev
- sudo apt-get install -qq libjack-dev libasound2-dev portaudio19-dev

before_script:
- git fetch --unshallow --tags -q

script:
- source /opt/qt515/bin/qt515-env.sh
- cmake .
- make
- sudo make install
