language: cpp

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install libqt4-dev libjack-dev libasound2-dev

before_script:
- ./autogen.sh

script:
- ./configure --enable-qt4
- make
- sudo make install
