language: cpp

sudo: required
dist: bionic

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt-5.14.2-bionic
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt514base qt514tools qt514x11extras libgl-dev; source /opt/qt514/bin/qt514-env.sh
- sudo apt-get install -qq libjack-dev libasound2-dev portaudio19-dev

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- ./configure
- make
- sudo make install
